# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.order_create_request_lines_inner_end_user_info_inner import OrderCreateRequestLinesInnerEndUserInfoInner

class TestOrderCreateRequestLinesInnerEndUserInfoInner(unittest.TestCase):
    """OrderCreateRequestLinesInnerEndUserInfoInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderCreateRequestLinesInnerEndUserInfoInner:
        """Test OrderCreateRequestLinesInnerEndUserInfoInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderCreateRequestLinesInnerEndUserInfoInner`
        """
        model = OrderCreateRequestLinesInnerEndUserInfoInner()
        if include_optional:
            return OrderCreateRequestLinesInnerEndUserInfoInner(
                end_user_type = '',
                end_user_id = '',
                contact = '',
                company_name = '',
                name1 = '',
                name2 = '',
                address_line1 = '',
                address_line2 = '',
                address_line3 = '',
                address_line4 = '',
                city = '',
                state = '',
                postal_code = '',
                country_code = '',
                phone_number = 1.337,
                email = ''
            )
        else:
            return OrderCreateRequestLinesInnerEndUserInfoInner(
        )
        """

    def testOrderCreateRequestLinesInnerEndUserInfoInner(self):
        """Test OrderCreateRequestLinesInnerEndUserInfoInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
