# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.quote_create_webhook_response_resource_products_inner import QuoteCreateWebhookResponseResourceProductsInner

class TestQuoteCreateWebhookResponseResourceProductsInner(unittest.TestCase):
    """QuoteCreateWebhookResponseResourceProductsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuoteCreateWebhookResponseResourceProductsInner:
        """Test QuoteCreateWebhookResponseResourceProductsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuoteCreateWebhookResponseResourceProductsInner`
        """
        model = QuoteCreateWebhookResponseResourceProductsInner()
        if include_optional:
            return QuoteCreateWebhookResponseResourceProductsInner(
                quote_product_guid = '',
                line_number = '',
                quantity = '',
                notes = '',
                ean = '',
                coo = '',
                ingram_part_number = '',
                vendor_part_number = '',
                description = '',
                weight = '',
                weight_uom = '',
                is_suggestion_product = '',
                vpn_category = '',
                quote_products_supplier_part_auxiliary_id = '',
                vendor_name = '',
                terms = '',
                price = xi.sdk.resellers.models.quote_create_webhook_response_resource_products_inner_price.quote_create_webhook_response_resource_products_inner_price(
                    quote_price = 56, 
                    msrp = 56, 
                    extended_msrp = 56, 
                    extended_quote_price = 56, 
                    discount_off_list = 1.337, )
            )
        else:
            return QuoteCreateWebhookResponseResourceProductsInner(
        )
        """

    def testQuoteCreateWebhookResponseResourceProductsInner(self):
        """Test QuoteCreateWebhookResponseResourceProductsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
