# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.price_and_availability_response_inner_pricing import PriceAndAvailabilityResponseInnerPricing

class TestPriceAndAvailabilityResponseInnerPricing(unittest.TestCase):
    """PriceAndAvailabilityResponseInnerPricing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PriceAndAvailabilityResponseInnerPricing:
        """Test PriceAndAvailabilityResponseInnerPricing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PriceAndAvailabilityResponseInnerPricing`
        """
        model = PriceAndAvailabilityResponseInnerPricing()
        if include_optional:
            return PriceAndAvailabilityResponseInnerPricing(
                currency_code = '',
                retail_price = 1.337,
                map_price = 1.337,
                customer_price = 1.337,
                special_bid_pricing_available = True,
                web_discounts_available = True
            )
        else:
            return PriceAndAvailabilityResponseInnerPricing(
        )
        """

    def testPriceAndAvailabilityResponseInnerPricing(self):
        """Test PriceAndAvailabilityResponseInnerPricing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
