# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.freight_response_freight_estimate_response_distribution_inner_carrier_list_inner import FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner

class TestFreightResponseFreightEstimateResponseDistributionInnerCarrierListInner(unittest.TestCase):
    """FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner:
        """Test FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner`
        """
        model = FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner()
        if include_optional:
            return FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner(
                carrier_code = '',
                ship_via = '',
                carrier_mode = '',
                estimated_freight_charge = '',
                days_in_transit = ''
            )
        else:
            return FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner(
        )
        """

    def testFreightResponseFreightEstimateResponseDistributionInnerCarrierListInner(self):
        """Test FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
