# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.api.freight_estimate_api import FreightEstimateApi


class TestFreightEstimateApi(unittest.TestCase):
    """FreightEstimateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FreightEstimateApi()

    def tearDown(self) -> None:
        pass

    def test_post_freightestimate(self) -> None:
        """Test case for post_freightestimate

        Freight Estimate
        """
        pass


if __name__ == '__main__':
    unittest.main()
