# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.api.product_catalog_api import ProductCatalogApi


class TestProductCatalogApi(unittest.TestCase):
    """ProductCatalogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductCatalogApi()

    def tearDown(self) -> None:
        pass

    def test_get_reseller_v6_productdetail(self) -> None:
        """Test case for get_reseller_v6_productdetail

        Product Details
        """
        pass

    def test_get_reseller_v6_productdetailcmp(self) -> None:
        """Test case for get_reseller_v6_productdetailcmp

        Product Details
        """
        pass

    def test_get_reseller_v6_productsearch(self) -> None:
        """Test case for get_reseller_v6_productsearch

        Search Products
        """
        pass

    def test_post_priceandavailability(self) -> None:
        """Test case for post_priceandavailability

        Price and Availability
        """
        pass


if __name__ == '__main__':
    unittest.main()
