# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.vendor_required_inforesponse_inner_vmf_additional_attributes_inner import VendorRequiredInforesponseInnerVmfAdditionalAttributesInner

class TestVendorRequiredInforesponseInnerVmfAdditionalAttributesInner(unittest.TestCase):
    """VendorRequiredInforesponseInnerVmfAdditionalAttributesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VendorRequiredInforesponseInnerVmfAdditionalAttributesInner:
        """Test VendorRequiredInforesponseInnerVmfAdditionalAttributesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VendorRequiredInforesponseInnerVmfAdditionalAttributesInner`
        """
        model = VendorRequiredInforesponseInnerVmfAdditionalAttributesInner()
        if include_optional:
            return VendorRequiredInforesponseInnerVmfAdditionalAttributesInner(
                vendor_name = '',
                product_id = '',
                additional_attributes = [
                    xi.sdk.resellers.models.vendor_required_inforesponse_inner_vmf_additional_attributes_inner_additional_attributes_inner.VendorRequiredInforesponse_inner_vmfAdditionalAttributes_inner_additionalAttributes_inner(
                        attribute_name = '', 
                        attribute_value = '', 
                        attribute_description = '', 
                        attribute_hint = '', 
                        choices = [
                            xi.sdk.resellers.models.vendor_required_inforesponse_inner_vmf_additional_attributes_inner_additional_attributes_inner_choices_inner.VendorRequiredInforesponse_inner_vmfAdditionalAttributes_inner_additionalAttributes_inner_choices_inner(
                                string = '', )
                            ], )
                    ]
            )
        else:
            return VendorRequiredInforesponseInnerVmfAdditionalAttributesInner(
        )
        """

    def testVendorRequiredInforesponseInnerVmfAdditionalAttributesInner(self):
        """Test VendorRequiredInforesponseInnerVmfAdditionalAttributesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
