# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.returns_details_response import ReturnsDetailsResponse

class TestReturnsDetailsResponse(unittest.TestCase):
    """ReturnsDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReturnsDetailsResponse:
        """Test ReturnsDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReturnsDetailsResponse`
        """
        model = ReturnsDetailsResponse()
        if include_optional:
            return ReturnsDetailsResponse(
                type_of_details = '',
                rma_claim_id = '',
                case_request_number = '',
                created_on = '',
                return_reason = '',
                reference_number = '',
                status = '',
                return_warehouse_address = '',
                products = [
                    xi.sdk.resellers.models.returns_details_response_products_inner.returnsDetailsResponse_products_inner(
                        ingram_line_number = 56, 
                        description = '', 
                        ingram_part_number = '', 
                        vendor_part_number = '', 
                        upc = '', 
                        invoice_date = '', 
                        invoice_number = '', 
                        customer_order_number = '', 
                        quantity = 1.337, 
                        unit_price = 1.337, 
                        extended_price = 1.337, 
                        status = '', 
                        return_branch = '', 
                        ship_from_branch = '', 
                        request_details = '', 
                        additional_details = '', )
                    ],
                sub_total = 1.337,
                tax = 1.337,
                additional_fees = 1.337,
                estimated_total = 1.337
            )
        else:
            return ReturnsDetailsResponse(
        )
        """

    def testReturnsDetailsResponse(self):
        """Test ReturnsDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
