# coding: utf-8

"""
    Reseller API

    For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xi.sdk.resellers.models.order_create_request import OrderCreateRequest

class TestOrderCreateRequest(unittest.TestCase):
    """OrderCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderCreateRequest:
        """Test OrderCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderCreateRequest`
        """
        model = OrderCreateRequest()
        if include_optional:
            return OrderCreateRequest(
                ordercreaterequest = xi.sdk.resellers.models.order_create_request_ordercreaterequest.orderCreateRequest_ordercreaterequest(
                    requestpreamble = xi.sdk.resellers.models.order_create_request_ordercreaterequest_requestpreamble.orderCreateRequest_ordercreaterequest_requestpreamble(
                        isocountrycode = '', 
                        customernumber = '10-123456 or 123456', ), 
                    ordercreatedetails = xi.sdk.resellers.models.order_create_request_ordercreaterequest_ordercreatedetails.orderCreateRequest_ordercreaterequest_ordercreatedetails(
                        customerponumber = '0', 
                        ordertype = 'Standard', 
                        enduserordernumber = '', 
                        billtosuffix = '', 
                        shiptosuffix = '', 
                        shiptoaddress = xi.sdk.resellers.models.order_create_request_ordercreaterequest_ordercreatedetails_shiptoaddress.orderCreateRequest_ordercreaterequest_ordercreatedetails_shiptoaddress(
                            attention = '“Mr. Customer”', 
                            addressline1 = '“Ingram Micro”', 
                            addressline2 = '3351 Michelson Dr', 
                            addressline3 = 'Ste 100 or ship to phone number', 
                            city = 'Irvine', 
                            state = 'CA', 
                            postalcode = '92712', 
                            countrycode = 'US', ), 
                        carriercode = '', 
                        thirdpartyfreightaccountnumber = '', 
                        specialbidnumber = '', 
                        lines = [
                            xi.sdk.resellers.models.order_create_request_ordercreaterequest_ordercreatedetails_lines_inner.orderCreateRequest_ordercreaterequest_ordercreatedetails_lines_inner(
                                linetype = 'P', 
                                linenumber = '', 
                                ingrampartnumber = '', 
                                quantity = '', 
                                vendorpartnumber = '', 
                                customerpartnumber = '', 
                                upc_code = '', 
                                warehouseid = '', 
                                unitprice = '', 
                                enduser = xi.sdk.resellers.models.order_create_request_ordercreaterequest_ordercreatedetails_lines_inner_enduser.orderCreateRequest_ordercreaterequest_ordercreatedetails_lines_inner_enduser(
                                    id = '', 
                                    addressline1 = '', 
                                    addressline2 = '', 
                                    addressline3 = '', 
                                    city = '', 
                                    state = '', 
                                    postalcode = '', 
                                    countrycode = '', 
                                    phonenumber = '', 
                                    extensionnumber = '', 
                                    faxnumber = '', 
                                    email = '', ), 
                                productextendedspecs = [
                                    xi.sdk.resellers.models.order_create_request_ordercreaterequest_ordercreatedetails_lines_inner_productextendedspecs_inner.orderCreateRequest_ordercreaterequest_ordercreatedetails_lines_inner_productextendedspecs_inner(
                                        attributename = 'shipfrom', 
                                        attributevalue = '', )
                                    ], )
                            ], 
                        extendedspecs = [
                            xi.sdk.resellers.models.order_create_request_ordercreaterequest_ordercreatedetails_extendedspecs_inner.orderCreateRequest_ordercreaterequest_ordercreatedetails_extendedspecs_inner(
                                attributename = 'Isdirectshiporder', 
                                attributevalue = '', )
                            ], ), )
            )
        else:
            return OrderCreateRequest(
        )
        """

    def testOrderCreateRequest(self):
        """Test OrderCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
