# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.returns_details_response_products_inner import ReturnsDetailsResponseProductsInner

class TestReturnsDetailsResponseProductsInner(unittest.TestCase):
    """ReturnsDetailsResponseProductsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReturnsDetailsResponseProductsInner:
        """Test ReturnsDetailsResponseProductsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReturnsDetailsResponseProductsInner`
        """
        model = ReturnsDetailsResponseProductsInner()
        if include_optional:
            return ReturnsDetailsResponseProductsInner(
                ingram_line_number = 56,
                description = '',
                ingram_part_number = '',
                vendor_part_number = '',
                upc = '',
                invoice_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                invoice_number = '',
                customer_order_number = '',
                request_details = '',
                quantity = 1.337,
                unit_price = 1.337,
                extended_price = 1.337,
                status = '',
                return_branch = '',
                ship_from_branch = ''
            )
        else:
            return ReturnsDetailsResponseProductsInner(
        )
        """

    def testReturnsDetailsResponseProductsInner(self):
        """Test ReturnsDetailsResponseProductsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
