# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.vmf_vri_additional_attribute_container import VmfVriAdditionalAttributeContainer

class TestVmfVriAdditionalAttributeContainer(unittest.TestCase):
    """VmfVriAdditionalAttributeContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VmfVriAdditionalAttributeContainer:
        """Test VmfVriAdditionalAttributeContainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VmfVriAdditionalAttributeContainer`
        """
        model = VmfVriAdditionalAttributeContainer()
        if include_optional:
            return VmfVriAdditionalAttributeContainer(
                vendor_name = '',
                product_id = '',
                additional_attributes = [
                    xi.sdk.resellers.models.additional_attribute.AdditionalAttribute(
                        attribute_name = '', 
                        attribute_value = '', 
                        attribute_description = '', 
                        attribute_hint = '', 
                        attribute_required = '', 
                        choices = [
                            xi.sdk.resellers.models.additional_attribute.AdditionalAttribute(
                                attribute_name = '', 
                                attribute_value = '', 
                                attribute_description = '', 
                                attribute_hint = '', 
                                attribute_required = '', )
                            ], )
                    ]
            )
        else:
            return VmfVriAdditionalAttributeContainer(
        )
        """

    def testVmfVriAdditionalAttributeContainer(self):
        """Test VmfVriAdditionalAttributeContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
