# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.quote_search_response import QuoteSearchResponse

class TestQuoteSearchResponse(unittest.TestCase):
    """QuoteSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuoteSearchResponse:
        """Test QuoteSearchResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuoteSearchResponse`
        """
        model = QuoteSearchResponse()
        if include_optional:
            return QuoteSearchResponse(
                records_found = 56,
                page_size = 56,
                page_number = 56,
                quotes = [
                    xi.sdk.resellers.models.quote_search_response_quotes_inner.QuoteSearchResponse_quotes_inner(
                        quote_name = '', 
                        quote_number = '', 
                        revision = '', 
                        end_user_contact = '', 
                        special_bid_number = '', 
                        quote_total = 1.337, 
                        quote_status = '', 
                        ingram_quote_date = '', 
                        last_modified_date = '', 
                        ingram_quote_expiry_date = '', 
                        vendor = '', 
                        created_by = '', )
                    ]
            )
        else:
            return QuoteSearchResponse(
        )
        """

    def testQuoteSearchResponse(self):
        """Test QuoteSearchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
