# coding: utf-8

"""
    XI Sdk Resellers

    For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xi.sdk.resellers.models.order_create_v7_request_lines_inner_warranty_info_inner import OrderCreateV7RequestLinesInnerWarrantyInfoInner

class TestOrderCreateV7RequestLinesInnerWarrantyInfoInner(unittest.TestCase):
    """OrderCreateV7RequestLinesInnerWarrantyInfoInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderCreateV7RequestLinesInnerWarrantyInfoInner:
        """Test OrderCreateV7RequestLinesInnerWarrantyInfoInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderCreateV7RequestLinesInnerWarrantyInfoInner`
        """
        model = OrderCreateV7RequestLinesInnerWarrantyInfoInner()
        if include_optional:
            return OrderCreateV7RequestLinesInnerWarrantyInfoInner(
                hardware_line_link = '',
                warranty_line_link = '',
                direct_line_link = '',
                serial_info = [
                    xi.sdk.resellers.models.order_create_v7_request_lines_inner_warranty_info_inner_serial_info_inner.order_create_v7_request_lines_inner_warrantyInfo_inner_serialInfo_inner(
                        date_of_purchase = '', 
                        ship_date = '', 
                        primary_serial_number = '', 
                        secondary_serial_number = '', )
                    ]
            )
        else:
            return OrderCreateV7RequestLinesInnerWarrantyInfoInner(
        )
        """

    def testOrderCreateV7RequestLinesInnerWarrantyInfoInner(self):
        """Test OrderCreateV7RequestLinesInnerWarrantyInfoInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
