# coding: utf-8

"""
    Reseller API

    For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from xi.sdk.resellers.models.invoice_detail_response_serviceresponse_responsepreamble import InvoiceDetailResponseServiceresponseResponsepreamble
from xi.sdk.resellers.models.order_create_response_serviceresponse_ordercreateresponse_inner import OrderCreateResponseServiceresponseOrdercreateresponseInner
from xi.sdk.resellers.models.order_create_response_serviceresponse_ordersummary import OrderCreateResponseServiceresponseOrdersummary
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OrderCreateResponseServiceresponse(BaseModel):
    """
    OrderCreateResponseServiceresponse
    """ # noqa: E501
    responsepreamble: Optional[InvoiceDetailResponseServiceresponseResponsepreamble] = None
    ordersummary: Optional[OrderCreateResponseServiceresponseOrdersummary] = None
    ordercreateresponse: Optional[List[OrderCreateResponseServiceresponseOrdercreateresponseInner]] = Field(default=None, description="Collection of orders")
    __properties: ClassVar[List[str]] = ["responsepreamble", "ordersummary", "ordercreateresponse"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderCreateResponseServiceresponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of responsepreamble
        if self.responsepreamble:
            _dict['responsepreamble'] = self.responsepreamble.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ordersummary
        if self.ordersummary:
            _dict['ordersummary'] = self.ordersummary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ordercreateresponse (list)
        _items = []
        if self.ordercreateresponse:
            for _item in self.ordercreateresponse:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ordercreateresponse'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OrderCreateResponseServiceresponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "responsepreamble": InvoiceDetailResponseServiceresponseResponsepreamble.from_dict(obj.get("responsepreamble")) if obj.get("responsepreamble") is not None else None,
            "ordersummary": OrderCreateResponseServiceresponseOrdersummary.from_dict(obj.get("ordersummary")) if obj.get("ordersummary") is not None else None,
            "ordercreateresponse": [OrderCreateResponseServiceresponseOrdercreateresponseInner.from_dict(_item) for _item in obj.get("ordercreateresponse")] if obj.get("ordercreateresponse") is not None else None
        })
        return _obj


