# coding: utf-8

"""
    Reseller API

    For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.

    The version of the OpenAPI document: 6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from xi.sdk.resellers.models.order_search_response_service_response_ordersearchresponse_orders_inner import OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OrderSearchResponseServiceResponseOrdersearchresponse(BaseModel):
    """
    OrderSearchResponseServiceResponseOrdersearchresponse
    """ # noqa: E501
    ordersfound: StrictStr = Field(description="Number of records found in the search result")
    pagesize: Optional[StrictStr] = Field(default=None, description="The submitted pagesize, default is 25")
    pagenumber: Optional[StrictStr] = Field(default=None, description="The submitted pager number, default is 1")
    orders: Optional[List[OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner]] = Field(default=None, description="An array of orders in the search result")
    __properties: ClassVar[List[str]] = ["ordersfound", "pagesize", "pagenumber", "orders"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderSearchResponseServiceResponseOrdersearchresponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in orders (list)
        _items = []
        if self.orders:
            for _item in self.orders:
                if _item:
                    _items.append(_item.to_dict())
            _dict['orders'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OrderSearchResponseServiceResponseOrdersearchresponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ordersfound": obj.get("ordersfound"),
            "pagesize": obj.get("pagesize"),
            "pagenumber": obj.get("pagenumber"),
            "orders": [OrderSearchResponseServiceResponseOrdersearchresponseOrdersInner.from_dict(_item) for _item in obj.get("orders")] if obj.get("orders") is not None else None
        })
        return _obj


