# coding: utf-8

"""
    XI Sdk Resellers

    For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from xi.sdk.resellers.models.renewals_search_request_date_type import RenewalsSearchRequestDateType
from xi.sdk.resellers.models.renewals_search_request_status import RenewalsSearchRequestStatus
from typing import Optional, Set
from typing_extensions import Self

class RenewalsSearchRequest(BaseModel):
    """
    RenewalsSearchRequest
    """ # noqa: E501
    status: Optional[RenewalsSearchRequestStatus] = None
    date_type: Optional[RenewalsSearchRequestDateType] = Field(default=None, alias="dateType")
    vendor: Optional[StrictStr] = Field(default=None, description="The name of the Vendor.")
    end_user: Optional[StrictStr] = Field(default=None, description="The name of the enduser. ", alias="endUser")
    __properties: ClassVar[List[str]] = ["status", "dateType", "vendor", "endUser"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RenewalsSearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of date_type
        if self.date_type:
            _dict['dateType'] = self.date_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RenewalsSearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": RenewalsSearchRequestStatus.from_dict(obj["status"]) if obj.get("status") is not None else None,
            "dateType": RenewalsSearchRequestDateType.from_dict(obj["dateType"]) if obj.get("dateType") is not None else None,
            "vendor": obj.get("vendor"),
            "endUser": obj.get("endUser")
        })
        return _obj


